#define CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_X_SELECTED y
#define CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_Y 0x00
#define CONFIG_MIPI_DCS_ADDRESS_MODE_MIRROR_X 0x40
#define CONFIG_MIPI_DCS_ADDRESS_MODE_SWAP_XY 0x00
#define CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_X 0x00
#define CONFIG_MIPI_DCS_ADDRESS_MODE_FLIP_Y 0x00
#define CONFIG_MIPI_DCS_PIXEL_FORMAT_16BIT_SELECTED y
#define CONFIG_MIPI_DISPLAY_PIXEL_FORMAT 0x55
#define CONFIG_MIPI_DISPLAY_WIDTH 240
#define CONFIG_MIPI_DISPLAY_DEPTH 16
#define CONFIG_MIPI_DISPLAY_HEIGHT 320
#define CONFIG_MIPI_DISPLAY_OFFSET_X 0
#define CONFIG_MIPI_DISPLAY_OFFSET_Y 0
#define CONFIG_MIPI_DCS_ADDRESS_MODE_BGR_SELECTED y
#define CONFIG_MIPI_DCS_ADDRESS_MODE_BGR 0x08
#define CONFIG_SPI_CLOCK_SPEED_HZ 40000000
#define CONFIG_MIPI_DISPLAY_PIN_MISO 12
#define CONFIG_MIPI_DISPLAY_PIN_MOSI 23
#define CONFIG_MIPI_DISPLAY_PIN_CLK 18
#define CONFIG_MIPI_DISPLAY_PIN_CS 27
#define CONFIG_MIPI_DISPLAY_PIN_DC 32
#define CONFIG_MIPI_DISPLAY_PIN_RST 5
#define CONFIG_MIPI_DISPLAY_PIN_BL 4
//#define CONFIG_HAGL_HAL_USE_DOUBLE_BUFFERING 
//#define CONFIG_HAGL_HAL_USE_TRIPLE_BUFFERING 
#define CONFIG_HAGL_HAL_NO_BUFFERING 
#define EXAMPLE_ESP_MAXIMUM_RETRY 5
#define CONFIG_MIPI_DCS_PIXEL_FORMAT_16BIT_SELECTED
#define CONFIG_ESP_WIFI_SSID "WAUDUBON"
#define CONFIG_ESP_WIFI_PASSWORD "298 W Audubon Dr"
#define CONFIG_ESP_WIFI_CHANNEL 11
#define CONFIG_MAX_STA_CONN 3
#define CONFIG_WEATHER_LATITUDE "37.98"
#define CONFIG_WEATHER_LONGITUDE "-85.71"
#define CONFIG_WEATHER_API_KEY "0e40f74ecc24c41f6df71c302267dfba"